from app import db
from app.models import Order, Product, OrderDetail


order = Order.query.get(int(10248))
product = Product.query.get(int(11))
od0 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od0)
order = Order.query.get(int(10248))
product = Product.query.get(int(42))
od1 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od1)
order = Order.query.get(int(10248))
product = Product.query.get(int(72))
od2 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od2)
order = Order.query.get(int(10249))
product = Product.query.get(int(14))
od3 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od3)
order = Order.query.get(int(10249))
product = Product.query.get(int(51))
od4 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od4)
order = Order.query.get(int(10250))
product = Product.query.get(int(41))
od5 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od5)
order = Order.query.get(int(10250))
product = Product.query.get(int(51))
od6 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od6)
order = Order.query.get(int(10250))
product = Product.query.get(int(65))
od7 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od7)
order = Order.query.get(int(10251))
product = Product.query.get(int(22))
od8 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od8)
order = Order.query.get(int(10251))
product = Product.query.get(int(57))
od9 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od9)
order = Order.query.get(int(10251))
product = Product.query.get(int(65))
od10 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od10)
order = Order.query.get(int(10252))
product = Product.query.get(int(20))
od11 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od11)
order = Order.query.get(int(10252))
product = Product.query.get(int(33))
od12 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od12)
order = Order.query.get(int(10252))
product = Product.query.get(int(60))
od13 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od13)
order = Order.query.get(int(10253))
product = Product.query.get(int(31))
od14 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od14)
order = Order.query.get(int(10253))
product = Product.query.get(int(39))
od15 = OrderDetail(order=order, product=product, quantity=42)
db.session.add(od15)
order = Order.query.get(int(10253))
product = Product.query.get(int(49))
od16 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od16)
order = Order.query.get(int(10254))
product = Product.query.get(int(24))
od17 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od17)
order = Order.query.get(int(10254))
product = Product.query.get(int(55))
od18 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od18)
order = Order.query.get(int(10254))
product = Product.query.get(int(74))
od19 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od19)
order = Order.query.get(int(10255))
product = Product.query.get(int(2))
od20 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od20)
order = Order.query.get(int(10255))
product = Product.query.get(int(16))
od21 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od21)
order = Order.query.get(int(10255))
product = Product.query.get(int(36))
od22 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od22)
order = Order.query.get(int(10255))
product = Product.query.get(int(59))
od23 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od23)
order = Order.query.get(int(10256))
product = Product.query.get(int(53))
od24 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od24)
order = Order.query.get(int(10256))
product = Product.query.get(int(77))
od25 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od25)
order = Order.query.get(int(10257))
product = Product.query.get(int(27))
od26 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od26)
order = Order.query.get(int(10257))
product = Product.query.get(int(39))
od27 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od27)
order = Order.query.get(int(10257))
product = Product.query.get(int(77))
od28 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od28)
order = Order.query.get(int(10258))
product = Product.query.get(int(2))
od29 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od29)
order = Order.query.get(int(10258))
product = Product.query.get(int(5))
od30 = OrderDetail(order=order, product=product, quantity=65)
db.session.add(od30)
order = Order.query.get(int(10258))
product = Product.query.get(int(32))
od31 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od31)
order = Order.query.get(int(10259))
product = Product.query.get(int(21))
od32 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od32)
order = Order.query.get(int(10259))
product = Product.query.get(int(37))
od33 = OrderDetail(order=order, product=product, quantity=1)
db.session.add(od33)
order = Order.query.get(int(10260))
product = Product.query.get(int(41))
od34 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od34)
order = Order.query.get(int(10260))
product = Product.query.get(int(57))
od35 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od35)
order = Order.query.get(int(10260))
product = Product.query.get(int(62))
od36 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od36)
order = Order.query.get(int(10260))
product = Product.query.get(int(70))
od37 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od37)
order = Order.query.get(int(10261))
product = Product.query.get(int(21))
od38 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od38)
order = Order.query.get(int(10261))
product = Product.query.get(int(35))
od39 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od39)
order = Order.query.get(int(10262))
product = Product.query.get(int(5))
od40 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od40)
order = Order.query.get(int(10262))
product = Product.query.get(int(7))
od41 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od41)
order = Order.query.get(int(10262))
product = Product.query.get(int(56))
od42 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od42)
order = Order.query.get(int(10263))
product = Product.query.get(int(16))
od43 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od43)
order = Order.query.get(int(10263))
product = Product.query.get(int(24))
od44 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od44)
order = Order.query.get(int(10263))
product = Product.query.get(int(30))
od45 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od45)
order = Order.query.get(int(10263))
product = Product.query.get(int(74))
od46 = OrderDetail(order=order, product=product, quantity=36)
db.session.add(od46)
order = Order.query.get(int(10264))
product = Product.query.get(int(2))
od47 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od47)
order = Order.query.get(int(10264))
product = Product.query.get(int(41))
od48 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od48)
order = Order.query.get(int(10265))
product = Product.query.get(int(17))
od49 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od49)
order = Order.query.get(int(10265))
product = Product.query.get(int(70))
od50 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od50)
order = Order.query.get(int(10266))
product = Product.query.get(int(12))
od51 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od51)
order = Order.query.get(int(10267))
product = Product.query.get(int(40))
od52 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od52)
order = Order.query.get(int(10267))
product = Product.query.get(int(59))
od53 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od53)
order = Order.query.get(int(10267))
product = Product.query.get(int(76))
od54 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od54)
order = Order.query.get(int(10268))
product = Product.query.get(int(29))
od55 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od55)
order = Order.query.get(int(10268))
product = Product.query.get(int(72))
od56 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od56)
order = Order.query.get(int(10269))
product = Product.query.get(int(33))
od57 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od57)
order = Order.query.get(int(10269))
product = Product.query.get(int(72))
od58 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od58)
order = Order.query.get(int(10270))
product = Product.query.get(int(36))
od59 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od59)
order = Order.query.get(int(10270))
product = Product.query.get(int(43))
od60 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od60)
order = Order.query.get(int(10271))
product = Product.query.get(int(33))
od61 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od61)
order = Order.query.get(int(10272))
product = Product.query.get(int(20))
od62 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od62)
order = Order.query.get(int(10272))
product = Product.query.get(int(31))
od63 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od63)
order = Order.query.get(int(10272))
product = Product.query.get(int(72))
od64 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od64)
order = Order.query.get(int(10273))
product = Product.query.get(int(10))
od65 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od65)
order = Order.query.get(int(10273))
product = Product.query.get(int(31))
od66 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od66)
order = Order.query.get(int(10273))
product = Product.query.get(int(33))
od67 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od67)
order = Order.query.get(int(10273))
product = Product.query.get(int(40))
od68 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od68)
order = Order.query.get(int(10273))
product = Product.query.get(int(76))
od69 = OrderDetail(order=order, product=product, quantity=33)
db.session.add(od69)
order = Order.query.get(int(10274))
product = Product.query.get(int(71))
od70 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od70)
order = Order.query.get(int(10274))
product = Product.query.get(int(72))
od71 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od71)
order = Order.query.get(int(10275))
product = Product.query.get(int(24))
od72 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od72)
order = Order.query.get(int(10275))
product = Product.query.get(int(59))
od73 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od73)
order = Order.query.get(int(10276))
product = Product.query.get(int(10))
od74 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od74)
order = Order.query.get(int(10276))
product = Product.query.get(int(13))
od75 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od75)
order = Order.query.get(int(10277))
product = Product.query.get(int(28))
od76 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od76)
order = Order.query.get(int(10277))
product = Product.query.get(int(62))
od77 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od77)
order = Order.query.get(int(10278))
product = Product.query.get(int(44))
od78 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od78)
order = Order.query.get(int(10278))
product = Product.query.get(int(59))
od79 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od79)
order = Order.query.get(int(10278))
product = Product.query.get(int(63))
od80 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od80)
order = Order.query.get(int(10278))
product = Product.query.get(int(73))
od81 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od81)
order = Order.query.get(int(10279))
product = Product.query.get(int(17))
od82 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od82)
order = Order.query.get(int(10280))
product = Product.query.get(int(24))
od83 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od83)
order = Order.query.get(int(10280))
product = Product.query.get(int(55))
od84 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od84)
order = Order.query.get(int(10280))
product = Product.query.get(int(75))
od85 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od85)
order = Order.query.get(int(10281))
product = Product.query.get(int(19))
od86 = OrderDetail(order=order, product=product, quantity=1)
db.session.add(od86)
order = Order.query.get(int(10281))
product = Product.query.get(int(24))
od87 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od87)
order = Order.query.get(int(10281))
product = Product.query.get(int(35))
od88 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od88)
order = Order.query.get(int(10282))
product = Product.query.get(int(30))
od89 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od89)
order = Order.query.get(int(10282))
product = Product.query.get(int(57))
od90 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od90)
order = Order.query.get(int(10283))
product = Product.query.get(int(15))
od91 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od91)
order = Order.query.get(int(10283))
product = Product.query.get(int(19))
od92 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od92)
order = Order.query.get(int(10283))
product = Product.query.get(int(60))
od93 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od93)
order = Order.query.get(int(10283))
product = Product.query.get(int(72))
od94 = OrderDetail(order=order, product=product, quantity=3)
db.session.add(od94)
order = Order.query.get(int(10284))
product = Product.query.get(int(27))
od95 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od95)
order = Order.query.get(int(10284))
product = Product.query.get(int(44))
od96 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od96)
order = Order.query.get(int(10284))
product = Product.query.get(int(60))
od97 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od97)
order = Order.query.get(int(10284))
product = Product.query.get(int(67))
od98 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od98)
order = Order.query.get(int(10285))
product = Product.query.get(int(1))
od99 = OrderDetail(order=order, product=product, quantity=45)
db.session.add(od99)
order = Order.query.get(int(10285))
product = Product.query.get(int(40))
od100 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od100)
order = Order.query.get(int(10285))
product = Product.query.get(int(53))
od101 = OrderDetail(order=order, product=product, quantity=36)
db.session.add(od101)
order = Order.query.get(int(10286))
product = Product.query.get(int(35))
od102 = OrderDetail(order=order, product=product, quantity=100)
db.session.add(od102)
order = Order.query.get(int(10286))
product = Product.query.get(int(62))
od103 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od103)
order = Order.query.get(int(10287))
product = Product.query.get(int(16))
od104 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od104)
order = Order.query.get(int(10287))
product = Product.query.get(int(34))
od105 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od105)
order = Order.query.get(int(10287))
product = Product.query.get(int(46))
od106 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od106)
order = Order.query.get(int(10288))
product = Product.query.get(int(54))
od107 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od107)
order = Order.query.get(int(10288))
product = Product.query.get(int(68))
od108 = OrderDetail(order=order, product=product, quantity=3)
db.session.add(od108)
order = Order.query.get(int(10289))
product = Product.query.get(int(3))
od109 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od109)
order = Order.query.get(int(10289))
product = Product.query.get(int(64))
od110 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od110)
order = Order.query.get(int(10290))
product = Product.query.get(int(5))
od111 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od111)
order = Order.query.get(int(10290))
product = Product.query.get(int(29))
od112 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od112)
order = Order.query.get(int(10290))
product = Product.query.get(int(49))
od113 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od113)
order = Order.query.get(int(10290))
product = Product.query.get(int(77))
od114 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od114)
order = Order.query.get(int(10291))
product = Product.query.get(int(13))
od115 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od115)
order = Order.query.get(int(10291))
product = Product.query.get(int(44))
od116 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od116)
order = Order.query.get(int(10291))
product = Product.query.get(int(51))
od117 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od117)
order = Order.query.get(int(10292))
product = Product.query.get(int(20))
od118 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od118)
order = Order.query.get(int(10293))
product = Product.query.get(int(18))
od119 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od119)
order = Order.query.get(int(10293))
product = Product.query.get(int(24))
od120 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od120)
order = Order.query.get(int(10293))
product = Product.query.get(int(63))
od121 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od121)
order = Order.query.get(int(10293))
product = Product.query.get(int(75))
od122 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od122)
order = Order.query.get(int(10294))
product = Product.query.get(int(1))
od123 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od123)
order = Order.query.get(int(10294))
product = Product.query.get(int(17))
od124 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od124)
order = Order.query.get(int(10294))
product = Product.query.get(int(43))
od125 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od125)
order = Order.query.get(int(10294))
product = Product.query.get(int(60))
od126 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od126)
order = Order.query.get(int(10294))
product = Product.query.get(int(75))
od127 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od127)
order = Order.query.get(int(10295))
product = Product.query.get(int(56))
od128 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od128)
order = Order.query.get(int(10296))
product = Product.query.get(int(11))
od129 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od129)
order = Order.query.get(int(10296))
product = Product.query.get(int(16))
od130 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od130)
order = Order.query.get(int(10296))
product = Product.query.get(int(69))
od131 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od131)
order = Order.query.get(int(10297))
product = Product.query.get(int(39))
od132 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od132)
order = Order.query.get(int(10297))
product = Product.query.get(int(72))
od133 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od133)
order = Order.query.get(int(10298))
product = Product.query.get(int(2))
od134 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od134)
order = Order.query.get(int(10298))
product = Product.query.get(int(36))
od135 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od135)
order = Order.query.get(int(10298))
product = Product.query.get(int(59))
od136 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od136)
order = Order.query.get(int(10298))
product = Product.query.get(int(62))
od137 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od137)
order = Order.query.get(int(10299))
product = Product.query.get(int(19))
od138 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od138)
order = Order.query.get(int(10299))
product = Product.query.get(int(70))
od139 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od139)
order = Order.query.get(int(10300))
product = Product.query.get(int(66))
od140 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od140)
order = Order.query.get(int(10300))
product = Product.query.get(int(68))
od141 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od141)
order = Order.query.get(int(10301))
product = Product.query.get(int(40))
od142 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od142)
order = Order.query.get(int(10301))
product = Product.query.get(int(56))
od143 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od143)
order = Order.query.get(int(10302))
product = Product.query.get(int(17))
od144 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od144)
order = Order.query.get(int(10302))
product = Product.query.get(int(28))
od145 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od145)
order = Order.query.get(int(10302))
product = Product.query.get(int(43))
od146 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od146)
order = Order.query.get(int(10303))
product = Product.query.get(int(40))
od147 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od147)
order = Order.query.get(int(10303))
product = Product.query.get(int(65))
od148 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od148)
order = Order.query.get(int(10303))
product = Product.query.get(int(68))
od149 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od149)
order = Order.query.get(int(10304))
product = Product.query.get(int(49))
od150 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od150)
order = Order.query.get(int(10304))
product = Product.query.get(int(59))
od151 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od151)
order = Order.query.get(int(10304))
product = Product.query.get(int(71))
od152 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od152)
order = Order.query.get(int(10305))
product = Product.query.get(int(18))
od153 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od153)
order = Order.query.get(int(10305))
product = Product.query.get(int(29))
od154 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od154)
order = Order.query.get(int(10305))
product = Product.query.get(int(39))
od155 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od155)
order = Order.query.get(int(10306))
product = Product.query.get(int(30))
od156 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od156)
order = Order.query.get(int(10306))
product = Product.query.get(int(53))
od157 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od157)
order = Order.query.get(int(10306))
product = Product.query.get(int(54))
od158 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od158)
order = Order.query.get(int(10307))
product = Product.query.get(int(62))
od159 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od159)
order = Order.query.get(int(10307))
product = Product.query.get(int(68))
od160 = OrderDetail(order=order, product=product, quantity=3)
db.session.add(od160)
order = Order.query.get(int(10308))
product = Product.query.get(int(69))
od161 = OrderDetail(order=order, product=product, quantity=1)
db.session.add(od161)
order = Order.query.get(int(10308))
product = Product.query.get(int(70))
od162 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od162)
order = Order.query.get(int(10309))
product = Product.query.get(int(4))
od163 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od163)
order = Order.query.get(int(10309))
product = Product.query.get(int(6))
od164 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od164)
order = Order.query.get(int(10309))
product = Product.query.get(int(42))
od165 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od165)
order = Order.query.get(int(10309))
product = Product.query.get(int(43))
od166 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od166)
order = Order.query.get(int(10309))
product = Product.query.get(int(71))
od167 = OrderDetail(order=order, product=product, quantity=3)
db.session.add(od167)
order = Order.query.get(int(10310))
product = Product.query.get(int(16))
od168 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od168)
order = Order.query.get(int(10310))
product = Product.query.get(int(62))
od169 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od169)
order = Order.query.get(int(10311))
product = Product.query.get(int(42))
od170 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od170)
order = Order.query.get(int(10311))
product = Product.query.get(int(69))
od171 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od171)
order = Order.query.get(int(10312))
product = Product.query.get(int(28))
od172 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od172)
order = Order.query.get(int(10312))
product = Product.query.get(int(43))
od173 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od173)
order = Order.query.get(int(10312))
product = Product.query.get(int(53))
od174 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od174)
order = Order.query.get(int(10312))
product = Product.query.get(int(75))
od175 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od175)
order = Order.query.get(int(10313))
product = Product.query.get(int(36))
od176 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od176)
order = Order.query.get(int(10314))
product = Product.query.get(int(32))
od177 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od177)
order = Order.query.get(int(10314))
product = Product.query.get(int(58))
od178 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od178)
order = Order.query.get(int(10314))
product = Product.query.get(int(62))
od179 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od179)
order = Order.query.get(int(10315))
product = Product.query.get(int(34))
od180 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od180)
order = Order.query.get(int(10315))
product = Product.query.get(int(70))
od181 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od181)
order = Order.query.get(int(10316))
product = Product.query.get(int(41))
od182 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od182)
order = Order.query.get(int(10316))
product = Product.query.get(int(62))
od183 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od183)
order = Order.query.get(int(10317))
product = Product.query.get(int(1))
od184 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od184)
order = Order.query.get(int(10318))
product = Product.query.get(int(41))
od185 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od185)
order = Order.query.get(int(10318))
product = Product.query.get(int(76))
od186 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od186)
order = Order.query.get(int(10319))
product = Product.query.get(int(17))
od187 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od187)
order = Order.query.get(int(10319))
product = Product.query.get(int(28))
od188 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od188)
order = Order.query.get(int(10319))
product = Product.query.get(int(76))
od189 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od189)
order = Order.query.get(int(10320))
product = Product.query.get(int(71))
od190 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od190)
order = Order.query.get(int(10321))
product = Product.query.get(int(35))
od191 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od191)
order = Order.query.get(int(10322))
product = Product.query.get(int(52))
od192 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od192)
order = Order.query.get(int(10323))
product = Product.query.get(int(15))
od193 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od193)
order = Order.query.get(int(10323))
product = Product.query.get(int(25))
od194 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od194)
order = Order.query.get(int(10323))
product = Product.query.get(int(39))
od195 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od195)
order = Order.query.get(int(10324))
product = Product.query.get(int(16))
od196 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od196)
order = Order.query.get(int(10324))
product = Product.query.get(int(35))
od197 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od197)
order = Order.query.get(int(10324))
product = Product.query.get(int(46))
od198 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od198)
order = Order.query.get(int(10324))
product = Product.query.get(int(59))
od199 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od199)
order = Order.query.get(int(10324))
product = Product.query.get(int(63))
od200 = OrderDetail(order=order, product=product, quantity=80)
db.session.add(od200)
order = Order.query.get(int(10325))
product = Product.query.get(int(6))
od201 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od201)
order = Order.query.get(int(10325))
product = Product.query.get(int(13))
od202 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od202)
order = Order.query.get(int(10325))
product = Product.query.get(int(14))
od203 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od203)
order = Order.query.get(int(10325))
product = Product.query.get(int(31))
od204 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od204)
order = Order.query.get(int(10325))
product = Product.query.get(int(72))
od205 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od205)
order = Order.query.get(int(10326))
product = Product.query.get(int(4))
od206 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od206)
order = Order.query.get(int(10326))
product = Product.query.get(int(57))
od207 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od207)
order = Order.query.get(int(10326))
product = Product.query.get(int(75))
od208 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od208)
order = Order.query.get(int(10327))
product = Product.query.get(int(2))
od209 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od209)
order = Order.query.get(int(10327))
product = Product.query.get(int(11))
od210 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od210)
order = Order.query.get(int(10327))
product = Product.query.get(int(30))
od211 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od211)
order = Order.query.get(int(10327))
product = Product.query.get(int(58))
od212 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od212)
order = Order.query.get(int(10328))
product = Product.query.get(int(59))
od213 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od213)
order = Order.query.get(int(10328))
product = Product.query.get(int(65))
od214 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od214)
order = Order.query.get(int(10328))
product = Product.query.get(int(68))
od215 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od215)
order = Order.query.get(int(10329))
product = Product.query.get(int(19))
od216 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od216)
order = Order.query.get(int(10329))
product = Product.query.get(int(30))
od217 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od217)
order = Order.query.get(int(10329))
product = Product.query.get(int(38))
od218 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od218)
order = Order.query.get(int(10329))
product = Product.query.get(int(56))
od219 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od219)
order = Order.query.get(int(10330))
product = Product.query.get(int(26))
od220 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od220)
order = Order.query.get(int(10330))
product = Product.query.get(int(72))
od221 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od221)
order = Order.query.get(int(10331))
product = Product.query.get(int(54))
od222 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od222)
order = Order.query.get(int(10332))
product = Product.query.get(int(18))
od223 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od223)
order = Order.query.get(int(10332))
product = Product.query.get(int(42))
od224 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od224)
order = Order.query.get(int(10332))
product = Product.query.get(int(47))
od225 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od225)
order = Order.query.get(int(10333))
product = Product.query.get(int(14))
od226 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od226)
order = Order.query.get(int(10333))
product = Product.query.get(int(21))
od227 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od227)
order = Order.query.get(int(10333))
product = Product.query.get(int(71))
od228 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od228)
order = Order.query.get(int(10334))
product = Product.query.get(int(52))
od229 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od229)
order = Order.query.get(int(10334))
product = Product.query.get(int(68))
od230 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od230)
order = Order.query.get(int(10335))
product = Product.query.get(int(2))
od231 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od231)
order = Order.query.get(int(10335))
product = Product.query.get(int(31))
od232 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od232)
order = Order.query.get(int(10335))
product = Product.query.get(int(32))
od233 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od233)
order = Order.query.get(int(10335))
product = Product.query.get(int(51))
od234 = OrderDetail(order=order, product=product, quantity=48)
db.session.add(od234)
order = Order.query.get(int(10336))
product = Product.query.get(int(4))
od235 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od235)
order = Order.query.get(int(10337))
product = Product.query.get(int(23))
od236 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od236)
order = Order.query.get(int(10337))
product = Product.query.get(int(26))
od237 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od237)
order = Order.query.get(int(10337))
product = Product.query.get(int(36))
od238 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od238)
order = Order.query.get(int(10337))
product = Product.query.get(int(37))
od239 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od239)
order = Order.query.get(int(10337))
product = Product.query.get(int(72))
od240 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od240)
order = Order.query.get(int(10338))
product = Product.query.get(int(17))
od241 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od241)
order = Order.query.get(int(10338))
product = Product.query.get(int(30))
od242 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od242)
order = Order.query.get(int(10339))
product = Product.query.get(int(4))
od243 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od243)
order = Order.query.get(int(10339))
product = Product.query.get(int(17))
od244 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od244)
order = Order.query.get(int(10339))
product = Product.query.get(int(62))
od245 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od245)
order = Order.query.get(int(10340))
product = Product.query.get(int(18))
od246 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od246)
order = Order.query.get(int(10340))
product = Product.query.get(int(41))
od247 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od247)
order = Order.query.get(int(10340))
product = Product.query.get(int(43))
od248 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od248)
order = Order.query.get(int(10341))
product = Product.query.get(int(33))
od249 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od249)
order = Order.query.get(int(10341))
product = Product.query.get(int(59))
od250 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od250)
order = Order.query.get(int(10342))
product = Product.query.get(int(2))
od251 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od251)
order = Order.query.get(int(10342))
product = Product.query.get(int(31))
od252 = OrderDetail(order=order, product=product, quantity=56)
db.session.add(od252)
order = Order.query.get(int(10342))
product = Product.query.get(int(36))
od253 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od253)
order = Order.query.get(int(10342))
product = Product.query.get(int(55))
od254 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od254)
order = Order.query.get(int(10343))
product = Product.query.get(int(64))
od255 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od255)
order = Order.query.get(int(10343))
product = Product.query.get(int(68))
od256 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od256)
order = Order.query.get(int(10343))
product = Product.query.get(int(76))
od257 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od257)
order = Order.query.get(int(10344))
product = Product.query.get(int(4))
od258 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od258)
order = Order.query.get(int(10344))
product = Product.query.get(int(8))
od259 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od259)
order = Order.query.get(int(10345))
product = Product.query.get(int(8))
od260 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od260)
order = Order.query.get(int(10345))
product = Product.query.get(int(19))
od261 = OrderDetail(order=order, product=product, quantity=80)
db.session.add(od261)
order = Order.query.get(int(10345))
product = Product.query.get(int(42))
od262 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od262)
order = Order.query.get(int(10346))
product = Product.query.get(int(17))
od263 = OrderDetail(order=order, product=product, quantity=36)
db.session.add(od263)
order = Order.query.get(int(10346))
product = Product.query.get(int(56))
od264 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od264)
order = Order.query.get(int(10347))
product = Product.query.get(int(25))
od265 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od265)
order = Order.query.get(int(10347))
product = Product.query.get(int(39))
od266 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od266)
order = Order.query.get(int(10347))
product = Product.query.get(int(40))
od267 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od267)
order = Order.query.get(int(10347))
product = Product.query.get(int(75))
od268 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od268)
order = Order.query.get(int(10348))
product = Product.query.get(int(1))
od269 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od269)
order = Order.query.get(int(10348))
product = Product.query.get(int(23))
od270 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od270)
order = Order.query.get(int(10349))
product = Product.query.get(int(54))
od271 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od271)
order = Order.query.get(int(10350))
product = Product.query.get(int(50))
od272 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od272)
order = Order.query.get(int(10350))
product = Product.query.get(int(69))
od273 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od273)
order = Order.query.get(int(10351))
product = Product.query.get(int(38))
od274 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od274)
order = Order.query.get(int(10351))
product = Product.query.get(int(41))
od275 = OrderDetail(order=order, product=product, quantity=13)
db.session.add(od275)
order = Order.query.get(int(10351))
product = Product.query.get(int(44))
od276 = OrderDetail(order=order, product=product, quantity=77)
db.session.add(od276)
order = Order.query.get(int(10351))
product = Product.query.get(int(65))
od277 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od277)
order = Order.query.get(int(10352))
product = Product.query.get(int(24))
od278 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od278)
order = Order.query.get(int(10352))
product = Product.query.get(int(54))
od279 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od279)
order = Order.query.get(int(10353))
product = Product.query.get(int(11))
od280 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od280)
order = Order.query.get(int(10353))
product = Product.query.get(int(38))
od281 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od281)
order = Order.query.get(int(10354))
product = Product.query.get(int(1))
od282 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od282)
order = Order.query.get(int(10354))
product = Product.query.get(int(29))
od283 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od283)
order = Order.query.get(int(10355))
product = Product.query.get(int(24))
od284 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od284)
order = Order.query.get(int(10355))
product = Product.query.get(int(57))
od285 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od285)
order = Order.query.get(int(10356))
product = Product.query.get(int(31))
od286 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od286)
order = Order.query.get(int(10356))
product = Product.query.get(int(55))
od287 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od287)
order = Order.query.get(int(10356))
product = Product.query.get(int(69))
od288 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od288)
order = Order.query.get(int(10357))
product = Product.query.get(int(10))
od289 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od289)
order = Order.query.get(int(10357))
product = Product.query.get(int(26))
od290 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od290)
order = Order.query.get(int(10357))
product = Product.query.get(int(60))
od291 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od291)
order = Order.query.get(int(10358))
product = Product.query.get(int(24))
od292 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od292)
order = Order.query.get(int(10358))
product = Product.query.get(int(34))
od293 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od293)
order = Order.query.get(int(10358))
product = Product.query.get(int(36))
od294 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od294)
order = Order.query.get(int(10359))
product = Product.query.get(int(16))
od295 = OrderDetail(order=order, product=product, quantity=56)
db.session.add(od295)
order = Order.query.get(int(10359))
product = Product.query.get(int(31))
od296 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od296)
order = Order.query.get(int(10359))
product = Product.query.get(int(60))
od297 = OrderDetail(order=order, product=product, quantity=80)
db.session.add(od297)
order = Order.query.get(int(10360))
product = Product.query.get(int(28))
od298 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od298)
order = Order.query.get(int(10360))
product = Product.query.get(int(29))
od299 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od299)
order = Order.query.get(int(10360))
product = Product.query.get(int(38))
od300 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od300)
order = Order.query.get(int(10360))
product = Product.query.get(int(49))
od301 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od301)
order = Order.query.get(int(10360))
product = Product.query.get(int(54))
od302 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od302)
order = Order.query.get(int(10361))
product = Product.query.get(int(39))
od303 = OrderDetail(order=order, product=product, quantity=54)
db.session.add(od303)
order = Order.query.get(int(10361))
product = Product.query.get(int(60))
od304 = OrderDetail(order=order, product=product, quantity=55)
db.session.add(od304)
order = Order.query.get(int(10362))
product = Product.query.get(int(25))
od305 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od305)
order = Order.query.get(int(10362))
product = Product.query.get(int(51))
od306 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od306)
order = Order.query.get(int(10362))
product = Product.query.get(int(54))
od307 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od307)
order = Order.query.get(int(10363))
product = Product.query.get(int(31))
od308 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od308)
order = Order.query.get(int(10363))
product = Product.query.get(int(75))
od309 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od309)
order = Order.query.get(int(10363))
product = Product.query.get(int(76))
od310 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od310)
order = Order.query.get(int(10364))
product = Product.query.get(int(69))
od311 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od311)
order = Order.query.get(int(10364))
product = Product.query.get(int(71))
od312 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od312)
order = Order.query.get(int(10365))
product = Product.query.get(int(11))
od313 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od313)
order = Order.query.get(int(10366))
product = Product.query.get(int(65))
od314 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od314)
order = Order.query.get(int(10366))
product = Product.query.get(int(77))
od315 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od315)
order = Order.query.get(int(10367))
product = Product.query.get(int(34))
od316 = OrderDetail(order=order, product=product, quantity=36)
db.session.add(od316)
order = Order.query.get(int(10367))
product = Product.query.get(int(54))
od317 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od317)
order = Order.query.get(int(10367))
product = Product.query.get(int(65))
od318 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od318)
order = Order.query.get(int(10367))
product = Product.query.get(int(77))
od319 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od319)
order = Order.query.get(int(10368))
product = Product.query.get(int(21))
od320 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od320)
order = Order.query.get(int(10368))
product = Product.query.get(int(28))
od321 = OrderDetail(order=order, product=product, quantity=13)
db.session.add(od321)
order = Order.query.get(int(10368))
product = Product.query.get(int(57))
od322 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od322)
order = Order.query.get(int(10368))
product = Product.query.get(int(64))
od323 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od323)
order = Order.query.get(int(10369))
product = Product.query.get(int(29))
od324 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od324)
order = Order.query.get(int(10369))
product = Product.query.get(int(56))
od325 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od325)
order = Order.query.get(int(10370))
product = Product.query.get(int(1))
od326 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od326)
order = Order.query.get(int(10370))
product = Product.query.get(int(64))
od327 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od327)
order = Order.query.get(int(10370))
product = Product.query.get(int(74))
od328 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od328)
order = Order.query.get(int(10371))
product = Product.query.get(int(36))
od329 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od329)
order = Order.query.get(int(10372))
product = Product.query.get(int(20))
od330 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od330)
order = Order.query.get(int(10372))
product = Product.query.get(int(38))
od331 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od331)
order = Order.query.get(int(10372))
product = Product.query.get(int(60))
od332 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od332)
order = Order.query.get(int(10372))
product = Product.query.get(int(72))
od333 = OrderDetail(order=order, product=product, quantity=42)
db.session.add(od333)
order = Order.query.get(int(10373))
product = Product.query.get(int(58))
od334 = OrderDetail(order=order, product=product, quantity=80)
db.session.add(od334)
order = Order.query.get(int(10373))
product = Product.query.get(int(71))
od335 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od335)
order = Order.query.get(int(10374))
product = Product.query.get(int(31))
od336 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od336)
order = Order.query.get(int(10374))
product = Product.query.get(int(58))
od337 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od337)
order = Order.query.get(int(10375))
product = Product.query.get(int(14))
od338 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od338)
order = Order.query.get(int(10375))
product = Product.query.get(int(54))
od339 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od339)
order = Order.query.get(int(10376))
product = Product.query.get(int(31))
od340 = OrderDetail(order=order, product=product, quantity=42)
db.session.add(od340)
order = Order.query.get(int(10377))
product = Product.query.get(int(28))
od341 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od341)
order = Order.query.get(int(10377))
product = Product.query.get(int(39))
od342 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od342)
order = Order.query.get(int(10378))
product = Product.query.get(int(71))
od343 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od343)
order = Order.query.get(int(10379))
product = Product.query.get(int(41))
od344 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od344)
order = Order.query.get(int(10379))
product = Product.query.get(int(63))
od345 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od345)
order = Order.query.get(int(10379))
product = Product.query.get(int(65))
od346 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od346)
order = Order.query.get(int(10380))
product = Product.query.get(int(30))
od347 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od347)
order = Order.query.get(int(10380))
product = Product.query.get(int(53))
od348 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od348)
order = Order.query.get(int(10380))
product = Product.query.get(int(60))
od349 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od349)
order = Order.query.get(int(10380))
product = Product.query.get(int(70))
od350 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od350)
order = Order.query.get(int(10381))
product = Product.query.get(int(74))
od351 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od351)
order = Order.query.get(int(10382))
product = Product.query.get(int(5))
od352 = OrderDetail(order=order, product=product, quantity=32)
db.session.add(od352)
order = Order.query.get(int(10382))
product = Product.query.get(int(18))
od353 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od353)
order = Order.query.get(int(10382))
product = Product.query.get(int(29))
od354 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od354)
order = Order.query.get(int(10382))
product = Product.query.get(int(33))
od355 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od355)
order = Order.query.get(int(10382))
product = Product.query.get(int(74))
od356 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od356)
order = Order.query.get(int(10383))
product = Product.query.get(int(13))
od357 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od357)
order = Order.query.get(int(10383))
product = Product.query.get(int(50))
od358 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od358)
order = Order.query.get(int(10383))
product = Product.query.get(int(56))
od359 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od359)
order = Order.query.get(int(10384))
product = Product.query.get(int(20))
od360 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od360)
order = Order.query.get(int(10384))
product = Product.query.get(int(60))
od361 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od361)
order = Order.query.get(int(10385))
product = Product.query.get(int(7))
od362 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od362)
order = Order.query.get(int(10385))
product = Product.query.get(int(60))
od363 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od363)
order = Order.query.get(int(10385))
product = Product.query.get(int(68))
od364 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od364)
order = Order.query.get(int(10386))
product = Product.query.get(int(24))
od365 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od365)
order = Order.query.get(int(10386))
product = Product.query.get(int(34))
od366 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od366)
order = Order.query.get(int(10387))
product = Product.query.get(int(24))
od367 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od367)
order = Order.query.get(int(10387))
product = Product.query.get(int(28))
od368 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od368)
order = Order.query.get(int(10387))
product = Product.query.get(int(59))
od369 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od369)
order = Order.query.get(int(10387))
product = Product.query.get(int(71))
od370 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od370)
order = Order.query.get(int(10388))
product = Product.query.get(int(45))
od371 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od371)
order = Order.query.get(int(10388))
product = Product.query.get(int(52))
od372 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od372)
order = Order.query.get(int(10388))
product = Product.query.get(int(53))
od373 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od373)
order = Order.query.get(int(10389))
product = Product.query.get(int(10))
od374 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od374)
order = Order.query.get(int(10389))
product = Product.query.get(int(55))
od375 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od375)
order = Order.query.get(int(10389))
product = Product.query.get(int(62))
od376 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od376)
order = Order.query.get(int(10389))
product = Product.query.get(int(70))
od377 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od377)
order = Order.query.get(int(10390))
product = Product.query.get(int(31))
od378 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od378)
order = Order.query.get(int(10390))
product = Product.query.get(int(35))
od379 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od379)
order = Order.query.get(int(10390))
product = Product.query.get(int(46))
od380 = OrderDetail(order=order, product=product, quantity=45)
db.session.add(od380)
order = Order.query.get(int(10390))
product = Product.query.get(int(72))
od381 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od381)
order = Order.query.get(int(10391))
product = Product.query.get(int(13))
od382 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od382)
order = Order.query.get(int(10392))
product = Product.query.get(int(69))
od383 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od383)
order = Order.query.get(int(10393))
product = Product.query.get(int(2))
od384 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od384)
order = Order.query.get(int(10393))
product = Product.query.get(int(14))
od385 = OrderDetail(order=order, product=product, quantity=42)
db.session.add(od385)
order = Order.query.get(int(10393))
product = Product.query.get(int(25))
od386 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od386)
order = Order.query.get(int(10393))
product = Product.query.get(int(26))
od387 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od387)
order = Order.query.get(int(10393))
product = Product.query.get(int(31))
od388 = OrderDetail(order=order, product=product, quantity=32)
db.session.add(od388)
order = Order.query.get(int(10394))
product = Product.query.get(int(13))
od389 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od389)
order = Order.query.get(int(10394))
product = Product.query.get(int(62))
od390 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od390)
order = Order.query.get(int(10395))
product = Product.query.get(int(46))
od391 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od391)
order = Order.query.get(int(10395))
product = Product.query.get(int(53))
od392 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od392)
order = Order.query.get(int(10395))
product = Product.query.get(int(69))
od393 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od393)
order = Order.query.get(int(10396))
product = Product.query.get(int(23))
od394 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od394)
order = Order.query.get(int(10396))
product = Product.query.get(int(71))
od395 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od395)
order = Order.query.get(int(10396))
product = Product.query.get(int(72))
od396 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od396)
order = Order.query.get(int(10397))
product = Product.query.get(int(21))
od397 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od397)
order = Order.query.get(int(10397))
product = Product.query.get(int(51))
od398 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od398)
order = Order.query.get(int(10398))
product = Product.query.get(int(35))
od399 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od399)
order = Order.query.get(int(10398))
product = Product.query.get(int(55))
od400 = OrderDetail(order=order, product=product, quantity=120)
db.session.add(od400)
order = Order.query.get(int(10399))
product = Product.query.get(int(68))
od401 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od401)
order = Order.query.get(int(10399))
product = Product.query.get(int(71))
od402 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od402)
order = Order.query.get(int(10399))
product = Product.query.get(int(76))
od403 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od403)
order = Order.query.get(int(10399))
product = Product.query.get(int(77))
od404 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od404)
order = Order.query.get(int(10400))
product = Product.query.get(int(29))
od405 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od405)
order = Order.query.get(int(10400))
product = Product.query.get(int(35))
od406 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od406)
order = Order.query.get(int(10400))
product = Product.query.get(int(49))
od407 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od407)
order = Order.query.get(int(10401))
product = Product.query.get(int(30))
od408 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od408)
order = Order.query.get(int(10401))
product = Product.query.get(int(56))
od409 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od409)
order = Order.query.get(int(10401))
product = Product.query.get(int(65))
od410 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od410)
order = Order.query.get(int(10401))
product = Product.query.get(int(71))
od411 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od411)
order = Order.query.get(int(10402))
product = Product.query.get(int(23))
od412 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od412)
order = Order.query.get(int(10402))
product = Product.query.get(int(63))
od413 = OrderDetail(order=order, product=product, quantity=65)
db.session.add(od413)
order = Order.query.get(int(10403))
product = Product.query.get(int(16))
od414 = OrderDetail(order=order, product=product, quantity=21)
db.session.add(od414)
order = Order.query.get(int(10403))
product = Product.query.get(int(48))
od415 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od415)
order = Order.query.get(int(10404))
product = Product.query.get(int(26))
od416 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od416)
order = Order.query.get(int(10404))
product = Product.query.get(int(42))
od417 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od417)
order = Order.query.get(int(10404))
product = Product.query.get(int(49))
od418 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od418)
order = Order.query.get(int(10405))
product = Product.query.get(int(3))
od419 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od419)
order = Order.query.get(int(10406))
product = Product.query.get(int(1))
od420 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od420)
order = Order.query.get(int(10406))
product = Product.query.get(int(21))
od421 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od421)
order = Order.query.get(int(10406))
product = Product.query.get(int(28))
od422 = OrderDetail(order=order, product=product, quantity=42)
db.session.add(od422)
order = Order.query.get(int(10406))
product = Product.query.get(int(36))
od423 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od423)
order = Order.query.get(int(10406))
product = Product.query.get(int(40))
od424 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od424)
order = Order.query.get(int(10407))
product = Product.query.get(int(11))
od425 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od425)
order = Order.query.get(int(10407))
product = Product.query.get(int(69))
od426 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od426)
order = Order.query.get(int(10407))
product = Product.query.get(int(71))
od427 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od427)
order = Order.query.get(int(10408))
product = Product.query.get(int(37))
od428 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od428)
order = Order.query.get(int(10408))
product = Product.query.get(int(54))
od429 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od429)
order = Order.query.get(int(10408))
product = Product.query.get(int(62))
od430 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od430)
order = Order.query.get(int(10409))
product = Product.query.get(int(14))
od431 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od431)
order = Order.query.get(int(10409))
product = Product.query.get(int(21))
od432 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od432)
order = Order.query.get(int(10410))
product = Product.query.get(int(33))
od433 = OrderDetail(order=order, product=product, quantity=49)
db.session.add(od433)
order = Order.query.get(int(10410))
product = Product.query.get(int(59))
od434 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od434)
order = Order.query.get(int(10411))
product = Product.query.get(int(41))
od435 = OrderDetail(order=order, product=product, quantity=25)
db.session.add(od435)
order = Order.query.get(int(10411))
product = Product.query.get(int(44))
od436 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od436)
order = Order.query.get(int(10411))
product = Product.query.get(int(59))
od437 = OrderDetail(order=order, product=product, quantity=9)
db.session.add(od437)
order = Order.query.get(int(10412))
product = Product.query.get(int(14))
od438 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od438)
order = Order.query.get(int(10413))
product = Product.query.get(int(1))
od439 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od439)
order = Order.query.get(int(10413))
product = Product.query.get(int(62))
od440 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od440)
order = Order.query.get(int(10413))
product = Product.query.get(int(76))
od441 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od441)
order = Order.query.get(int(10414))
product = Product.query.get(int(19))
od442 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od442)
order = Order.query.get(int(10414))
product = Product.query.get(int(33))
od443 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od443)
order = Order.query.get(int(10415))
product = Product.query.get(int(17))
od444 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od444)
order = Order.query.get(int(10415))
product = Product.query.get(int(33))
od445 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od445)
order = Order.query.get(int(10416))
product = Product.query.get(int(19))
od446 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od446)
order = Order.query.get(int(10416))
product = Product.query.get(int(53))
od447 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od447)
order = Order.query.get(int(10416))
product = Product.query.get(int(57))
od448 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od448)
order = Order.query.get(int(10417))
product = Product.query.get(int(38))
od449 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od449)
order = Order.query.get(int(10417))
product = Product.query.get(int(46))
od450 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od450)
order = Order.query.get(int(10417))
product = Product.query.get(int(68))
od451 = OrderDetail(order=order, product=product, quantity=36)
db.session.add(od451)
order = Order.query.get(int(10417))
product = Product.query.get(int(77))
od452 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od452)
order = Order.query.get(int(10418))
product = Product.query.get(int(2))
od453 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od453)
order = Order.query.get(int(10418))
product = Product.query.get(int(47))
od454 = OrderDetail(order=order, product=product, quantity=55)
db.session.add(od454)
order = Order.query.get(int(10418))
product = Product.query.get(int(61))
od455 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od455)
order = Order.query.get(int(10418))
product = Product.query.get(int(74))
od456 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od456)
order = Order.query.get(int(10419))
product = Product.query.get(int(60))
od457 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od457)
order = Order.query.get(int(10419))
product = Product.query.get(int(69))
od458 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od458)
order = Order.query.get(int(10420))
product = Product.query.get(int(9))
od459 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od459)
order = Order.query.get(int(10420))
product = Product.query.get(int(13))
od460 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od460)
order = Order.query.get(int(10420))
product = Product.query.get(int(70))
od461 = OrderDetail(order=order, product=product, quantity=8)
db.session.add(od461)
order = Order.query.get(int(10420))
product = Product.query.get(int(73))
od462 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od462)
order = Order.query.get(int(10421))
product = Product.query.get(int(19))
od463 = OrderDetail(order=order, product=product, quantity=4)
db.session.add(od463)
order = Order.query.get(int(10421))
product = Product.query.get(int(26))
od464 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od464)
order = Order.query.get(int(10421))
product = Product.query.get(int(53))
od465 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od465)
order = Order.query.get(int(10421))
product = Product.query.get(int(77))
od466 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od466)
order = Order.query.get(int(10422))
product = Product.query.get(int(26))
od467 = OrderDetail(order=order, product=product, quantity=2)
db.session.add(od467)
order = Order.query.get(int(10423))
product = Product.query.get(int(31))
od468 = OrderDetail(order=order, product=product, quantity=14)
db.session.add(od468)
order = Order.query.get(int(10423))
product = Product.query.get(int(59))
od469 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od469)
order = Order.query.get(int(10424))
product = Product.query.get(int(35))
od470 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od470)
order = Order.query.get(int(10424))
product = Product.query.get(int(38))
od471 = OrderDetail(order=order, product=product, quantity=49)
db.session.add(od471)
order = Order.query.get(int(10424))
product = Product.query.get(int(68))
od472 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od472)
order = Order.query.get(int(10425))
product = Product.query.get(int(55))
od473 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od473)
order = Order.query.get(int(10425))
product = Product.query.get(int(76))
od474 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od474)
order = Order.query.get(int(10426))
product = Product.query.get(int(56))
od475 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od475)
order = Order.query.get(int(10426))
product = Product.query.get(int(64))
od476 = OrderDetail(order=order, product=product, quantity=7)
db.session.add(od476)
order = Order.query.get(int(10427))
product = Product.query.get(int(14))
od477 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od477)
order = Order.query.get(int(10428))
product = Product.query.get(int(46))
od478 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od478)
order = Order.query.get(int(10429))
product = Product.query.get(int(50))
od479 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od479)
order = Order.query.get(int(10429))
product = Product.query.get(int(63))
od480 = OrderDetail(order=order, product=product, quantity=35)
db.session.add(od480)
order = Order.query.get(int(10430))
product = Product.query.get(int(17))
od481 = OrderDetail(order=order, product=product, quantity=45)
db.session.add(od481)
order = Order.query.get(int(10430))
product = Product.query.get(int(21))
od482 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od482)
order = Order.query.get(int(10430))
product = Product.query.get(int(56))
od483 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od483)
order = Order.query.get(int(10430))
product = Product.query.get(int(59))
od484 = OrderDetail(order=order, product=product, quantity=70)
db.session.add(od484)
order = Order.query.get(int(10431))
product = Product.query.get(int(17))
od485 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od485)
order = Order.query.get(int(10431))
product = Product.query.get(int(40))
od486 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od486)
order = Order.query.get(int(10431))
product = Product.query.get(int(47))
od487 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od487)
order = Order.query.get(int(10432))
product = Product.query.get(int(26))
od488 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od488)
order = Order.query.get(int(10432))
product = Product.query.get(int(54))
od489 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od489)
order = Order.query.get(int(10433))
product = Product.query.get(int(56))
od490 = OrderDetail(order=order, product=product, quantity=28)
db.session.add(od490)
order = Order.query.get(int(10434))
product = Product.query.get(int(11))
od491 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od491)
order = Order.query.get(int(10434))
product = Product.query.get(int(76))
od492 = OrderDetail(order=order, product=product, quantity=18)
db.session.add(od492)
order = Order.query.get(int(10435))
product = Product.query.get(int(2))
od493 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od493)
order = Order.query.get(int(10435))
product = Product.query.get(int(22))
od494 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od494)
order = Order.query.get(int(10435))
product = Product.query.get(int(72))
od495 = OrderDetail(order=order, product=product, quantity=10)
db.session.add(od495)
order = Order.query.get(int(10436))
product = Product.query.get(int(46))
od496 = OrderDetail(order=order, product=product, quantity=5)
db.session.add(od496)
order = Order.query.get(int(10436))
product = Product.query.get(int(56))
od497 = OrderDetail(order=order, product=product, quantity=40)
db.session.add(od497)
order = Order.query.get(int(10436))
product = Product.query.get(int(64))
od498 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od498)
order = Order.query.get(int(10436))
product = Product.query.get(int(75))
od499 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od499)
order = Order.query.get(int(10437))
product = Product.query.get(int(53))
od500 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od500)
order = Order.query.get(int(10438))
product = Product.query.get(int(19))
od501 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od501)
order = Order.query.get(int(10438))
product = Product.query.get(int(34))
od502 = OrderDetail(order=order, product=product, quantity=20)
db.session.add(od502)
order = Order.query.get(int(10438))
product = Product.query.get(int(57))
od503 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od503)
order = Order.query.get(int(10439))
product = Product.query.get(int(12))
od504 = OrderDetail(order=order, product=product, quantity=15)
db.session.add(od504)
order = Order.query.get(int(10439))
product = Product.query.get(int(16))
od505 = OrderDetail(order=order, product=product, quantity=16)
db.session.add(od505)
order = Order.query.get(int(10439))
product = Product.query.get(int(64))
od506 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od506)
order = Order.query.get(int(10439))
product = Product.query.get(int(74))
od507 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od507)
order = Order.query.get(int(10440))
product = Product.query.get(int(2))
od508 = OrderDetail(order=order, product=product, quantity=45)
db.session.add(od508)
order = Order.query.get(int(10440))
product = Product.query.get(int(16))
od509 = OrderDetail(order=order, product=product, quantity=49)
db.session.add(od509)
order = Order.query.get(int(10440))
product = Product.query.get(int(29))
od510 = OrderDetail(order=order, product=product, quantity=24)
db.session.add(od510)
order = Order.query.get(int(10440))
product = Product.query.get(int(61))
od511 = OrderDetail(order=order, product=product, quantity=90)
db.session.add(od511)
order = Order.query.get(int(10441))
product = Product.query.get(int(27))
od512 = OrderDetail(order=order, product=product, quantity=50)
db.session.add(od512)
order = Order.query.get(int(10442))
product = Product.query.get(int(11))
od513 = OrderDetail(order=order, product=product, quantity=30)
db.session.add(od513)
order = Order.query.get(int(10442))
product = Product.query.get(int(54))
od514 = OrderDetail(order=order, product=product, quantity=80)
db.session.add(od514)
order = Order.query.get(int(10442))
product = Product.query.get(int(66))
od515 = OrderDetail(order=order, product=product, quantity=60)
db.session.add(od515)
order = Order.query.get(int(10443))
product = Product.query.get(int(11))
od516 = OrderDetail(order=order, product=product, quantity=6)
db.session.add(od516)
order = Order.query.get(int(10443))
product = Product.query.get(int(28))
od517 = OrderDetail(order=order, product=product, quantity=12)
db.session.add(od517)

db.session.commit()

print('Dummy OrderDetails added to db -- SUCCESS')