
from app import app, db
from app.models import Product


p1 = Product(productname="Chais", supplier_id=1, category_id=1, unit="10 boxes x 20 bags", price=18)
db.session.add(p1)
p2 = Product(productname="Chang", supplier_id=1, category_id=1, unit="24 - 12 oz bottles", price=19)
db.session.add(p2)
p3 = Product(productname="Aniseed Syrup", supplier_id=1, category_id=2, unit="12 - 550 ml bottles", price=10)
db.session.add(p3)
p4 = Product(productname="Chef Anton's Cajun Seasoning", supplier_id=2, category_id=2, unit="48 - 6 oz jars", price=22)
db.session.add(p4)
p5 = Product(productname="Chef Anton's Gumbo Mix", supplier_id=2, category_id=2, unit="36 boxes", price=21.35)
db.session.add(p5)
p6 = Product(productname="Grandma's Boysenberry Spread", supplier_id=3, category_id=2, unit="12 - 8 oz jars", price=25)
db.session.add(p6)
p7 = Product(productname="Uncle Bob's Organic Dried Pears", supplier_id=3, category_id=7, unit="12 - 1 lb pkgs.", price=30)
db.session.add(p7)
p8 = Product(productname="Northwoods Cranberry Sauce", supplier_id=3, category_id=2, unit="12 - 12 oz jars", price=40)
db.session.add(p8)
p9 = Product(productname="Mishi Kobe Niku", supplier_id=4, category_id=6, unit="18 - 500 g pkgs.", price=97)
db.session.add(p9)
p10 = Product(productname="Ikura", supplier_id=4, category_id=8, unit="12 - 200 ml jars", price=31)
db.session.add(p10)
p11 = Product(productname="Queso Cabrales", supplier_id=5, category_id=4, unit="1 kg pkg.", price=21)
db.session.add(p11)
p12 = Product(productname="Queso Manchego La Pastora", supplier_id=5, category_id=4, unit="10 - 500 g pkgs.", price=38)
db.session.add(p12)
p13 = Product(productname="Konbu", supplier_id=6, category_id=8, unit="2 kg box", price=6)
db.session.add(p13)
p14 = Product(productname="Tofu", supplier_id=6, category_id=7, unit="40 - 100 g pkgs.", price=23.25)
db.session.add(p14)
p15 = Product(productname="Genen Shouyu", supplier_id=6, category_id=2, unit="24 - 250 ml bottles", price=15.5)
db.session.add(p15)
p16 = Product(productname="Pavlova", supplier_id=7, category_id=3, unit="32 - 500 g boxes", price=17.45)
db.session.add(p16)
p17 = Product(productname="Alice Mutton", supplier_id=7, category_id=6, unit="20 - 1 kg tins", price=39)
db.session.add(p17)
p18 = Product(productname="Carnarvon Tigers", supplier_id=7, category_id=8, unit="16 kg pkg.", price=62.5)
db.session.add(p18)
p19 = Product(productname="Teatime Chocolate Biscuits", supplier_id=8, category_id=3, unit="10 boxes x 12 pieces", price=9.2)
db.session.add(p19)
p20 = Product(productname="Sir Rodney's Marmalade", supplier_id=8, category_id=3, unit="30 gift boxes", price=81)
db.session.add(p20)
p21 = Product(productname="Sir Rodney's Scones", supplier_id=8, category_id=3, unit="24 pkgs. x 4 pieces", price=10)
db.session.add(p21)
p22 = Product(productname="Gustaf's Knäckebröd", supplier_id=9, category_id=5, unit="24 - 500 g pkgs.", price=21)
db.session.add(p22)
p23 = Product(productname="Tunnbröd", supplier_id=9, category_id=5, unit="12 - 250 g pkgs.", price=9)
db.session.add(p23)
p24 = Product(productname="Guaraná Fantástica", supplier_id=10, category_id=1, unit="12 - 355 ml cans", price=4.5)
db.session.add(p24)
p25 = Product(productname="NuNuCa Nuß-Nougat-Creme", supplier_id=11, category_id=3, unit="20 - 450 g glasses", price=14)
db.session.add(p25)
p26 = Product(productname="Gumbär Gummibärchen", supplier_id=11, category_id=3, unit="100 - 250 g bags", price=31.23)
db.session.add(p26)
p27 = Product(productname="Schoggi Schokolade", supplier_id=11, category_id=3, unit="100 - 100 g pieces", price=43.9)
db.session.add(p27)
p28 = Product(productname="Rössle Sauerkraut", supplier_id=12, category_id=7, unit="25 - 825 g cans", price=45.6)
db.session.add(p28)
p29 = Product(productname="Thüringer Rostbratwurst", supplier_id=12, category_id=6, unit="50 bags x 30 sausgs.", price=123.79)
db.session.add(p29)
p30 = Product(productname="Nord-Ost Matjeshering", supplier_id=13, category_id=8, unit="10 - 200 g glasses", price=25.89)
db.session.add(p30)
p31 = Product(productname="Gorgonzola Telino", supplier_id=14, category_id=4, unit="12 - 100 g pkgs", price=12.5)
db.session.add(p31)
p32 = Product(productname="Mascarpone Fabioli", supplier_id=14, category_id=4, unit="24 - 200 g pkgs.", price=32)
db.session.add(p32)
p33 = Product(productname="Geitost", supplier_id=15, category_id=4, unit="500 g", price=2.5)
db.session.add(p33)
p34 = Product(productname="Sasquatch Ale", supplier_id=16, category_id=1, unit="24 - 12 oz bottles", price=14)
db.session.add(p34)
p35 = Product(productname="Steeleye Stout", supplier_id=16, category_id=1, unit="24 - 12 oz bottles", price=18)
db.session.add(p35)
p36 = Product(productname="Inlagd Sill", supplier_id=17, category_id=8, unit="24 - 250 g jars", price=19)
db.session.add(p36)
p37 = Product(productname="Gravad lax", supplier_id=17, category_id=8, unit="12 - 500 g pkgs.", price=26)
db.session.add(p37)
p38 = Product(productname="Côte de Blaye", supplier_id=18, category_id=1, unit="12 - 75 cl bottles", price=263.5)
db.session.add(p38)
p39 = Product(productname="Chartreuse verte", supplier_id=18, category_id=1, unit="750 cc per bottle", price=18)
db.session.add(p39)
p40 = Product(productname="Boston Crab Meat", supplier_id=19, category_id=8, unit="24 - 4 oz tins", price=18.4)
db.session.add(p40)
p41 = Product(productname="Jack's New England Clam Chowder", supplier_id=19, category_id=8, unit="12 - 12 oz cans", price=9.65)
db.session.add(p41)
p42 = Product(productname="Singaporean Hokkien Fried Mee", supplier_id=20, category_id=5, unit="32 - 1 kg pkgs.", price=14)
db.session.add(p42)
p43 = Product(productname="Ipoh Coffee", supplier_id=20, category_id=1, unit="16 - 500 g tins", price=46)
db.session.add(p43)
p44 = Product(productname="Gula Malacca", supplier_id=20, category_id=2, unit="20 - 2 kg bags", price=19.45)
db.session.add(p44)
p45 = Product(productname="Røgede sild", supplier_id=21, category_id=8, unit="1k pkg.", price=9.5)
db.session.add(p45)
p46 = Product(productname="Spegesild", supplier_id=21, category_id=8, unit="4 - 450 g glasses", price=12)
db.session.add(p46)
p47 = Product(productname="Zaanse koeken", supplier_id=22, category_id=3, unit="10 - 4 oz boxes", price=9.5)
db.session.add(p47)
p48 = Product(productname="Chocolade", supplier_id=22, category_id=3, unit="10 pkgs.", price=12.75)
db.session.add(p48)
p49 = Product(productname="Maxilaku", supplier_id=23, category_id=3, unit="24 - 50 g pkgs.", price=20)
db.session.add(p49)
p50 = Product(productname="Valkoinen suklaa", supplier_id=23, category_id=3, unit="12 - 100 g bars", price=16.25)
db.session.add(p50)
p51 = Product(productname="Manjimup Dried Apples", supplier_id=24, category_id=7, unit="50 - 300 g pkgs.", price=53)
db.session.add(p51)
p52 = Product(productname="Filo Mix", supplier_id=24, category_id=5, unit="16 - 2 kg boxes", price=7)
db.session.add(p52)
p53 = Product(productname="Perth Pasties", supplier_id=24, category_id=6, unit="48 pieces", price=32.8)
db.session.add(p53)
p54 = Product(productname="Tourtière", supplier_id=25, category_id=6, unit="16 pies", price=7.45)
db.session.add(p54)
p55 = Product(productname="Pâté chinois", supplier_id=25, category_id=6, unit="24 boxes x 2 pies", price=24)
db.session.add(p55)
p56 = Product(productname="Gnocchi di nonna Alice", supplier_id=26, category_id=5, unit="24 - 250 g pkgs.", price=38)
db.session.add(p56)
p57 = Product(productname="Ravioli Angelo", supplier_id=26, category_id=5, unit="24 - 250 g pkgs.", price=19.5)
db.session.add(p57)
p58 = Product(productname="Escargots de Bourgogne", supplier_id=27, category_id=8, unit="24 pieces", price=13.25)
db.session.add(p58)
p59 = Product(productname="Raclette Courdavault", supplier_id=28, category_id=4, unit="5 kg pkg.", price=55)
db.session.add(p59)
p60 = Product(productname="Camembert Pierrot", supplier_id=28, category_id=4, unit="15 - 300 g rounds", price=34)
db.session.add(p60)
p61 = Product(productname="Sirop d'érable", supplier_id=29, category_id=2, unit="24 - 500 ml bottles", price=28.5)
db.session.add(p61)
p62 = Product(productname="Tarte au sucre", supplier_id=29, category_id=3, unit="48 pies", price=49.3)
db.session.add(p62)
p63 = Product(productname="Vegie-spread", supplier_id=7, category_id=2, unit="15 - 625 g jars", price=43.9)
db.session.add(p63)
p64 = Product(productname="Wimmers gute Semmelknödel", supplier_id=12, category_id=5, unit="20 bags x 4 pieces", price=33.25)
db.session.add(p64)
p65 = Product(productname="Louisiana Fiery Hot Pepper Sauce", supplier_id=2, category_id=2, unit="32 - 8 oz bottles", price=21.05)
db.session.add(p65)
p66 = Product(productname="Louisiana Hot Spiced Okra", supplier_id=2, category_id=2, unit="24 - 8 oz jars", price=17)
db.session.add(p66)
p67 = Product(productname="Laughing Lumberjack Lager", supplier_id=16, category_id=1, unit="24 - 12 oz bottles", price=14)
db.session.add(p67)
p68 = Product(productname="Scottish Longbreads", supplier_id=8, category_id=3, unit="10 boxes x 8 pieces", price=12.5)
db.session.add(p68)
p69 = Product(productname="Gudbrandsdalsost", supplier_id=15, category_id=4, unit="10 kg pkg.", price=36)
db.session.add(p69)
p70 = Product(productname="Outback Lager", supplier_id=7, category_id=1, unit="24 - 355 ml bottles", price=15)
db.session.add(p70)
p71 = Product(productname="Fløtemysost", supplier_id=15, category_id=4, unit="10 - 500 g pkgs.", price=21.5)
db.session.add(p71)
p72 = Product(productname="Mozzarella di Giovanni", supplier_id=14, category_id=4, unit="24 - 200 g pkgs.", price=34.8)
db.session.add(p72)
p73 = Product(productname="Röd Kaviar", supplier_id=17, category_id=8, unit="24 - 150 g jars", price=15)
db.session.add(p73)
p74 = Product(productname="Longlife Tofu", supplier_id=4, category_id=7, unit="5 kg pkg.", price=10)
db.session.add(p74)
p75 = Product(productname="Rhönbräu Klosterbier", supplier_id=12, category_id=1, unit="24 - 0.5 l bottles", price=7.75)
db.session.add(p75)
p76 = Product(productname="Lakkalikööri", supplier_id=23, category_id=1, unit="500 ml ", price=18)
db.session.add(p76)
p77 = Product(productname="Original Frankfurter grüne Soße", supplier_id=12, category_id=2, unit="12 boxes", price=13)
db.session.add(p77)
db.session.commit()

print("Added dummy products to the db to be used for development!")