"""Add employeeID, password_hash columns and add set_password, check_password, and avatar funcs to Employee table. This was to allow for two sets of users. The general public and employees will have different access and abilities.

Revision ID: 18f4e0722456
Revises: a9287f3ba5b0
Create Date: 2018-11-28 14:17:22.836263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f4e0722456'
down_revision = 'a9287f3ba5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employeeID', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_employee_employeeID'), 'employee', ['employeeID'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_employeeID'), table_name='employee')
    op.drop_column('employee', 'password_hash')
    op.drop_column('employee', 'employeeID')
    # ### end Alembic commands ###
