"""Add middlename column to user table.

Revision ID: 5a099a3dde86
Revises: 81162fe5d987
Create Date: 2018-11-29 00:29:52.750869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a099a3dde86'
down_revision = '81162fe5d987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middlename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middlename')
    # ### end Alembic commands ###
