"""Add created column to Product table.

Revision ID: b861c4f4fe8f
Revises: 6c9d78373dab
Create Date: 2019-01-18 15:22:01.775167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b861c4f4fe8f'
down_revision = '6c9d78373dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created')
    # ### end Alembic commands ###
